version: 2.1

orbs:
  k8s: circleci/kubernetes@1.3.1

jobs:
  kots:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - k8s/install-kubectl
      - run: curl https://kots.io/install | REPL_USE_SUDO=y bash
      - run: kubectl kots version
      - run:
          name: downgrade KOTS to v1.65.0
          # See https://docs.replicated.com/reference/kots-cli-getting-started#manually-download-and-install
          command: |
            curl -o kots_linux_amd64.tar.gz -L https://github.com/replicatedhq/kots/releases/download/v1.65.0/kots_linux_amd64.tar.gz
            tar xvf kots_linux_amd64.tar.gz
            sudo mv kots /usr/local/bin/kubectl-kots
      - run: kubectl kots version

workflows:
  main:
    jobs:
      - kots
