version: 2.1

orbs:
  k8s: circleci/kubernetes@1.3.1

jobs:
  kots:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - k8s/install-kubectl
      - run: curl https://kots.io/install | bash
      - run: kubectl kots version

workflows:
  main:
    jobs:
      - kots
